import { execFile } from 'node:child_process'
import { access, chmod, cp, lstat, mkdir, readFile, readlink, realpath, rename, rm, symlink, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { homedir } from 'node:os'
import { parseArgs, promisify } from 'node:util'
import { randomUUID } from 'node:crypto'
import { loadConfig, openDatabase, safeError } from '@jt-harness/memo'
import { configureFlowHooks, configureHooks, configureMonitorHooks, readJson, writeJson, quote } from '@jt-harness/codex-hooks'
import { installFlow } from './flow.ts'
import { configureProjectCodex, inspectNativeHooks, withCodex, type NativeHook, type NativeHookList } from './codex-client.ts'
import { phoenixStatus } from './phoenix.ts'

const execute = promisify(execFile)
const help = `jth init --project <id> [--workspace <path>] [--env-file <path>] [--trust] [--codex-memory off|inherit]
jth install --project <id> [--workspace <path>] [--env-file <path>] [--trust] [--codex-memory off|inherit]
jth install --cli [--from <已解压发行目录>] [--prefix <目录>] [--env-file <path>]
jth upgrade [--from <已解压发行目录>] [--prefix <目录>] [--workspace <项目目录>] [--trust]
jth doctor [--workspace <path>] [--env-file <path>]
jth uninstall [--workspace <path>]
init 复用项目安装，默认关闭本项目 Codex 原生记忆的读取和生成，并开启 update_plan；inherit 仅移除记忆的两个项目覆盖项，跟随上层配置。
install 接入项目，未传 --codex-memory 时保留原生记忆配置；--cli 安装 CLI 本体。upgrade 更新发行目录并同步当前项目。
doctor 只读检查，不调用模型；uninstall 移除项目接入，保留数据库、队列与凭据。
`

/** Trust only definitions regenerated by this installation, never similarly named third-party hooks. */
export function isManagedHook(hook: NativeHook, root: string, workspace: string, monitoring: boolean) {
  const events: Record<string, string[]> = { 'jth flow entry': ['userPromptSubmit'], 'jth memo declaration': ['stop'],
    'jth monitor': monitoring ? ['userPromptSubmit', 'stop', 'interrupt'] : [] }
  const prefix = [process.execPath, resolve(root, 'bin/jth.mjs')].map(quote).join(' ') + ' '
  return hook.source === 'project' && hook.sourcePath === resolve(workspace, '.codex/hooks.json')
    && Boolean(events[hook.statusMessage ?? '']?.includes(hook.eventName) && hook.command?.startsWith(prefix))
}

async function ownedRoot(skill: string) {
  const target = await readlink(skill).catch(error => { if (error.code === 'ENOENT') return null; throw error })
  if (!target) return null
  const root = resolve(dirname(skill), target, '../../../..')
  if (JSON.parse(await readFile(resolve(root, 'package.json'), 'utf8')).name !== 'jt-harness') throw new Error('已有 Skill 不属于 jt-harness；保留原文件')
  return root
}

/** Versioned, relocatable releases; keep credentials outside replaceable release directories. */
export async function installCli(source: string, prefix: string, envFile?: string) {
  const packageRoot = await realpath(source)
  const manifest = JSON.parse(await readFile(resolve(packageRoot, 'package.json'), 'utf8'))
  const build = manifest.jthDistribution?.build
  if (manifest.name !== 'jt-harness' || !/^[a-z0-9-]{8,80}$/.test(build ?? '')) throw new Error('需要独立发行目录；先运行 pnpm bundle 并解压发行包')
  await execute(process.execPath, [resolve(packageRoot, 'bin/jth.mjs'), '--help'], { timeout: 15000 })
  const home = resolve(prefix, 'share/jth'), target = resolve(home, 'releases', build), binary = resolve(prefix, 'bin/jth')
  const existing = await lstat(binary).catch(error => { if (error.code === 'ENOENT') return null; throw error })
  if (existing) {
    if (!existing.isSymbolicLink()) throw new Error('保留已有 jth 可执行文件；它不是本工具安装的链接')
    const prior = await realpath(binary)
    if (JSON.parse(await readFile(resolve(prior, '../../package.json'), 'utf8')).name !== 'jt-harness') throw new Error('保留不属于 jt-harness 的命令链接')
  }
  await mkdir(resolve(home, 'releases'), { recursive: true, mode: 0o700 })
  const sharedEnv = resolve(home, '.env')
  if (!await access(sharedEnv).then(() => true, () => false)) {
    if (envFile) await symlink(await realpath(envFile), sharedEnv)
    else await writeFile(sharedEnv, await readFile(resolve(packageRoot, '.env.example'), 'utf8'), { flag: 'wx', mode: 0o600 })
  }
  if (!await access(target).then(() => true, () => false)) {
    const staging = `${target}.${randomUUID()}.tmp`
    try {
      await cp(packageRoot, staging, { recursive: true, verbatimSymlinks: true, filter: path => path !== resolve(packageRoot, '.env') })
      await symlink(sharedEnv, resolve(staging, '.env'))
      await execute(process.execPath, [resolve(staging, 'bin/jth.mjs'), '--help'], { timeout: 15000 })
      await rename(staging, target)
    } finally { await rm(staging, { recursive: true, force: true }) }
  }
  await mkdir(dirname(binary), { recursive: true })
  const link = `${binary}.${randomUUID()}.tmp`
  await symlink(resolve(target, 'bin/jth.mjs'), link)
  await rename(link, binary)
  await chmod(resolve(target, 'bin/jth.mjs'), 0o755)
  return { status: 'installed', version: manifest.version, build, root: target, binary, envFile: sharedEnv }
}

export async function deliveryMain(root: string, args: string[]) {
  let config: Awaited<ReturnType<typeof loadConfig>> | undefined
  try {
    const { values, positionals } = parseArgs({ args, allowPositionals: true, options: {
      workspace: { type: 'string' }, 'env-file': { type: 'string' }, project: { type: 'string', multiple: true }, business: { type: 'string', multiple: true },
      from: { type: 'string' }, prefix: { type: 'string' }, cli: { type: 'boolean' }, trust: { type: 'boolean' }, help: { type: 'boolean', short: 'h' },
      'codex-memory': { type: 'string' },
    } })
    const [command] = positionals
    if (values.help) { process.stdout.write(help); return }
    if (positionals.length !== 1) throw new Error('参数数量不符；运行 jth install --help')
    const allowed: Record<string, string[]> = {
      init: ['workspace', 'env-file', 'project', 'business', 'trust', 'codex-memory'],
      install: ['workspace', 'env-file', 'project', 'business', 'from', 'prefix', 'cli', 'trust', 'codex-memory'],
      upgrade: ['workspace', 'from', 'prefix', 'trust'], doctor: ['workspace', 'env-file'], uninstall: ['workspace', 'env-file'],
    }
    if (!allowed[command] || Object.keys(values).some(key => !allowed[command].includes(key))) throw new Error(`${command} 参数不支持；运行 jth install --help`)
    const memoryPolicy = values['codex-memory'] ?? (command === 'init' ? 'off' : undefined)
    if (memoryPolicy !== undefined && memoryPolicy !== 'off' && memoryPolicy !== 'inherit') throw new Error('--codex-memory 仅支持 off 或 inherit')
    if (values.cli && (values.project || values.business || values.trust || memoryPolicy)) throw new Error('--cli 安装工具本体；项目接入请另用 jth init 或 jth install')
    if (values.cli && command !== 'install') throw new Error('--cli 仅用于 install')
    if ((values.from || values.prefix) && !values.cli && command !== 'upgrade') throw new Error('--from/--prefix 用于 install --cli 或 upgrade')
    const workspace = await realpath(resolve(values.workspace ?? process.cwd()))
    const output = (value: unknown) => process.stdout.write(JSON.stringify(value, null, 2) + '\n')
    if ((command === 'install' && values.cli) || (command === 'upgrade' && values.from)) {
      const installed = await installCli(resolve(values.from ?? root), resolve(values.prefix ?? resolve(homedir(), '.local')), values['env-file'])
      if (command === 'upgrade' && await access(resolve(workspace, '.jth/flow.json')).then(() => true, () => false)) {
        const updated = await execute(process.execPath, [resolve(installed.root, 'bin/jth.mjs'), 'upgrade', '--workspace', workspace, ...(values.trust ? ['--trust'] : [])])
        output({ ...installed, project: JSON.parse(updated.stdout) }); return
      }
      output(installed); return
    }
    const locator = await readJson(resolve(workspace, '.jth/flow.json')) as { envFile: string } | undefined
    config = await loadConfig(root, values['env-file'] ?? locator?.envFile)
    if (command === 'doctor') {
      const manifest = JSON.parse(await readFile(resolve(root, 'package.json'), 'utf8'))
      const checks: { name: string, status: string, detail?: unknown }[] = []
      checks.push({ name: 'cli', status: 'ok', detail: { version: manifest.version, node: process.version, standalone: Boolean(manifest.jthDistribution) } })
      checks.push({ name: 'configuration', status: config.databaseUrl ? 'ok' : 'error', detail: { envFile: config.envFile, embeddingConfigured: Boolean(config.embedding.space && config.embedding.apiKey) } })
      try {
        const pool = openDatabase(config, true)
        try {
          const result = await pool.query("SELECT kind,status,count(*)::int AS count FROM jt_memo.jobs GROUP BY kind,status")
          checks.push({ name: 'database', status: 'ok', detail: result.rows })
        } finally { await pool.end() }
      } catch (error) { checks.push({ name: 'database', status: 'error', detail: safeError(error, config) }) }
      try {
        const native = await inspectNativeHooks(workspace), own = native.hooks.filter(h => h.statusMessage?.startsWith('jth '))
        checks.push({ name: 'hooks', status: own.length && own.every(h => h.enabled && h.trustStatus === 'trusted') ? 'ok' : 'warning',
          detail: { hooks: own.map(({ statusMessage, eventName, enabled, trustStatus }) => ({ name: statusMessage, event: eventName, enabled, trustStatus })), errors: native.errors, warnings: native.warnings } })
      } catch (error) { checks.push({ name: 'hooks', status: 'warning', detail: safeError(error, config) }) }
      checks.push({ name: 'flow_entry', status: (await readJson(resolve(workspace, '.jth/flow-entry.json'))) ? 'ok' : 'warning', detail: await readJson(resolve(workspace, '.jth/flow-entry.json')) ?? '尚无触发记录；已安装不等于已执行' })
      const monitor = await readJson(resolve(workspace, '.jth/monitor.json')) as { enabled?: boolean } | undefined
      const phoenix = await phoenixStatus(config)
      checks.push({ name: 'monitor', status: !monitor?.enabled ? 'disabled' : phoenix.reachable ? 'ok' : 'warning', detail: {
        ...phoenix, enabled: Boolean(monitor?.enabled), lastExport: await readJson(resolve(workspace, '.jth/monitor/last-export.json')) ?? null } })
      output({ workspace, checks }); process.exitCode = checks.some(check => check.status === 'error') ? 1 : 0; return
    }
    const oldRoot = await ownedRoot(resolve(workspace, '.agents/skills/jth-flow'))
    if (command === 'uninstall') {
      await configureMonitorHooks(oldRoot ?? root, workspace, false)
      if (await readJson(resolve(workspace, '.jth/monitor.json'))) await writeJson(resolve(workspace, '.jth/monitor.json'), { enabled: false })
      const flow = await configureFlowHooks(oldRoot ?? root, workspace, false)
      const memo = await configureHooks(root, config, workspace, undefined, resolve(process.env.CODEX_HOME ?? resolve(homedir(), '.codex')))
      output({ flow, memo, data_preserved: true }); return
    }
    if (!['init', 'install', 'upgrade'].includes(command)) throw new Error('未知交付命令')
    const status = locator ? JSON.parse((await execute(process.execPath, [resolve(root, 'bin/jth.mjs'), 'flow', 'status', '--workspace', workspace])).stdout) : null
    const projects: string[] = values.project ?? status?.memo_scope?.project_ids ?? []
    const businesses: string[] = values.business ?? status?.memo_scope?.business_ids ?? []
    if (!projects.length && !businesses.length) throw new Error('首次安装需要 --project <id> 或 --business <id>')
    if (oldRoot && oldRoot !== await realpath(root)) await configureFlowHooks(oldRoot, workspace, false)
    const installed = await installFlow(root, workspace, config, { project_ids: projects, business_ids: businesses })
    const codexPreferences = memoryPolicy ? await configureProjectCodex(workspace, memoryPolicy, command === 'init') : {}
    const monitoring = Boolean((await readJson(resolve(workspace, '.jth/monitor.json')) as { enabled?: boolean } | undefined)?.enabled)
    if (monitoring) await configureMonitorHooks(root, workspace, true)
    if (values.trust) await withCodex(async call => {
      const result = await call('hooks/list', { cwds: [workspace] }) as NativeHookList
      const hooks = result.data[0].hooks.filter(h => isManagedHook(h, root, workspace, monitoring))
      if (!hooks.length) throw new Error('Codex 未发现项目 Hook；先信任项目配置层')
      await call('config/batchWrite', { edits: hooks.map(h => ({ keyPath: `hooks.state.${JSON.stringify(h.key)}.trusted_hash`, value: h.currentHash, mergeStrategy: 'replace' })), reloadUserConfig: true })
    })
    output({ ...installed, ...codexPreferences })
  } catch (error) { process.stderr.write(JSON.stringify({ error: safeError(error, config) }) + '\n'); process.exitCode = 1 }
}
